# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Dog Age Calculator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dog Age Calculator
pod 'RevealingSplashView'
end
